title: Jurong Lake District
url: https://www.jld.gov.sg
favicon: /images/July 2022 Update/Hero.jpg
colors:
  primary-color: "#225828"
  secondary-color: "#124596"
  media-colors:
    - title: media-color-one
      color: "#70c8e3"
    - title: media-color-two
      color: "#225828"
    - title: media-color-three
      color: "#62863a"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#62863a"
resources_name: Events-and-resources
description: A Place To Grow
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3n6guo2svnb73.amplifyapp.com/
prod: https://master.d3n6guo2svnb73.amplifyapp.com/
shareicon: /images/July 2022 Update/Hero.jpg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
